kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        # Replace GCLOUD_PROJECT with your project ID
        image: gcr.io/deft-manifest-297817/app:latest
        # This app listens on port 81 for web traffic by default.
        ports:
        - containerPort: 81
        env:
          - name: PORT
            value: "81"
