apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-python
  name: app-python
  namespace: ci-cd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        # Replace GCLOUD_PROJECT with your project ID
        image: gcr.io/universal-torch-305711/helloworld-gke:latest
        
        ports:
        - containerPort: 8081
          protocol: TCP
        
