apiVersion: v1 
kind: Service 
metadata:
  name: hello 
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - port: 8081
    targetPort: 8081 

---
apiVersion: extensions/v1beta1
kind: Ingress 
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: hello-ingress
  namespace: ci-cd 
spec:
  rules:
  - host: hello-app
    http:
      paths:
        - path: /
          backend:
            serviceName: app
            servicePort: 8081
