version: '3'

services:

  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
        - nginx
        - apache
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  nginx:
    depends_on:
        - reverseproxy
    image: nginx:alpine
    ports:
      - 8080:80
    restart: on-failure
 
  apache:
    depends_on:
        - reverseproxy
    image: httpd:alpine
    ports: 
      - 8081:80
    restart: on-failure
