version: '3.3'

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4242:80
    networks:
      - gitlab

    
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ee:latest'
    restart: unless-stopped
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://127.0.0.1:4242/gitlab'
       gitlab_rails['gitlab_shell_ssh_port'] = 2224
       nginx['listen_port'] = 80
       nginx['listen_https'] = false
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab


  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    user: root
    hostname: 'jenkins'
    ports:
      - '8081:8080'
      - '50000:50000'
    volumes:
      - './jenkins:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker:/usr/local/bin/docker'
    environment:
      - JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
      #- VIRTUAL_HOST=http://127.0.0.1:4242/jenkins
    networks:
      - gitlab


  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.1.0
    volumes:
      #- ./conf/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://127.0.0.1:4242/prometheus'
     #- '--web.route-prefix="/"'
    ports:
      - 9090:9090
    restart: always
    networks:
      - gitlab



  grgrafana:
    container_name: grafana
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      #- ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    networks:
      - gitlab
    environment:
      - GF_SERVER_DOMAIN="127.0.0.1"
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:4242/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH="true"
      - GF_SESSION_COOKIE_SECURE="false"

networks:
  gitlab:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  jenkins_home:

