kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        # Replace GCLOUD_PROJECT with your project ID
        image: gcr.io/deft-manifest-297817/github.com/mikadiablo/ydays-devops@sha256:2d996ff1abe1b13ad0cd59f3b33893e65851c4e381164b0ee0584fcb91ef627b
        # This app listens on port 81 for web traffic by default.
        ports:
        - containerPort: 8081
        env:
          - name: PORT
            value: "8081"
